spring:
    kafka:
        bootstrap-servers: "localhost:29092"

management:
    endpoints:
        web:
            exposure:
                include:
                  ["health", "live", "metrics", "prometheus"]

    endpoint:
        health:
            show-details: always
            show-components: always
            cache:
                time-to-live: 5s
